application: towel
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- admin_redirect: on

inbound_services:
- mail

handlers:
- url: /_ah/mail/ops@.+
  script: handle_incoming_email.py
  login: admin
    
- url: .*
  script: main.py
  login: required
